/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Tier1_Baked.glb')
  return (
    <group {...props} dispose={null} >
      <group>
        <group name="TIER_TRANSPARENT" >
          <mesh name="TIER1" castShadow receiveShadow geometry={nodes.TIER1.geometry} material={materials.TIER1} position={[1478.315, 298.341, 58.364]} />
          <mesh name="Cube" castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.holo_1} position={[-531.706, 178.786, -21.943]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Tier1_Baked.glb')
